### ISSUE TITLE
Unable to set text content type to support autofill

### ISSUE THREAD

**Issue by freemansion** [Fawxy/CBPinEntryView#11]
#### Issue
Native `UITextField` class has property called `textContentType`, which allows to specify expected information about semantic intent. 

I think it does make sense (especially for this library) to add same attribute  in order to support iOS 12 new feature like autofill OTP code.

More information you can read at the official website - https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view

**Comment by Fawxy** [comment]
Good idea. I will try to implement this next week

**Comment by freemansion** [comment]
Will make a PR soon.

**Comment by Fawxy** [comment]
Merged. sorry this took me so long 😬
