### ISSUE TITLE
Field background color not changing on entering pin

### ISSUE THREAD

**Issue by meets7** [Fawxy/CBPinEntryView#13]
![screen shot 2018-10-10 at 11 24 41 am](https://user-images.githubusercontent.com/6688825/46751056-19c42d00-cc7f-11e8-90df-e375df0d6e9a.png)

I am unable to find a field which will let me set the background color after entry. 

There is an entryBackgroundColour. But that sets the default background color.

Is there something similar to entryBorderColour and entryDefaultBorderColor?

**Comment by Fawxy** [comment]
Do you want to set the background on the currently editing field, or on any fields already filled?

**Comment by Fawxy** [comment]
I have adding a setting to change the background colour on the currently editing field, that behaves the same way as the border colour.

**Comment by meets7** [comment]
I was thinking of background color for an already filled field. Like in the attached image above, the background color of 5 (and not the 2nd circle).
