### ISSUE TITLE
Automatically submit on editing finished.

### ISSUE THREAD

**Issue by GeorgePadmore** [Fawxy/CBPinEntryView#14]
Kindly include the feature where we can automatically submit input or perform an action immediately on Editing Did End.
Currently you can only submit or perform an action by using a button.

If you already have this feature, then kindly show us how. thanks.

**Comment by Fawxy** [comment]
If you set your view controller as the delegate of the pin entry, there are two functions available `entryChanged` and `entryCompleted` (new in 1.6.2). Entry changed will give you a `completed` variable which will let you know if the text field has been changed so it's full, or `entryCompleted` will give you a callback when the entry is complete with a string of the currently entered text.
