### ISSUE TITLE
 length and spacing not changing when being set programmatically

### ISSUE THREAD

**Issue by AmineNac** [Fawxy/CBPinEntryView#17]
i'm trying to change the length and spacing of the PinEntryView programmatically but it want change, it just sticks to the settings that i've set into the storyboard.

pinView.length = 6
pinView.spacing = CGFloat(10)

**Comment by Fawxy** [comment]
It might be better to not set anything in the storyboard, and only set your length/spacing programatically. Can you let me know if that works?

**Comment by shengwanlin** [comment]
> It might be better to not set anything in the storyboard, and only set your length/spacing programatically. Can you let me know if that works?

It not works when set length/spacing programatically

**Comment by Fawxy** [comment]
I've allowed programmatic changes  - it will reset the view though
