### ISSUE TITLE
Swift 5 support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [Fawxy/CBPinEntryView#18]
## Expected Results

No warning to convert CBPinEntryView.framework to Swift 5

## Actual Results

Xcode created warnings to convert CBPinEntryView.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by jlaws** [comment]
Ping

**Comment by Fawxy** [comment]
This should be fixed. Let me know if it's not.
